name: Send Feishu Notification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  send_feushu_notification:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Notify
        env:
          ACTIONS_FEISHU_TAG: 'v1.3.1'
          INPUT_WEBHOOK: "${{ secrets.FEISHU_ROBOT_WEBHOOK_URL }}"
          INPUT_MESSAGE_TYPE: "post"
          INPUT_TITLE: "有代码合入"
          INPUT_CONTENT: "from Github Action\n
                        View in Repo: ${{ secrets.VIEW_GITHUB_REPOSITORY }}"
        run: |
          wget -q https://github.com/xiachufang/actions-feishu/releases/download/${{ env.ACTIONS_FEISHU_TAG }}/linux-amd64-actions-feishu.tar.gz
          tar zxf linux-amd64-actions-feishu.tar.gz feishu
          ./feishu
